{{- if and (not .Values.existingSecretName) .Values.hcloudApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-fip-controller.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-fip-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  HCLOUD_API_TOKEN: {{ .Values.hcloudApiToken | quote }}
{{- end }}
