{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcloud-fip-controller.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-fip-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hcloud-fip-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.healthCheck.port }}
      targetPort: health
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hcloud-fip-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-fip-controller.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "hcloud-fip-controller.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      {{- with .Values.monitoring.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
{{- end }}
